### ISSUE TITLE
Catch test dependency

### ISSUE THREAD

**Issue by bcdonovan** [BBN-Q/libx6#21]
Tests now have dependency on a catch.hpp [here](https://github.com/BBN-Q/libx6/blob/master/test/run_tests.cpp#L2). Are you using [philsquared/Catch](https://github.com/philsquared/Catch)?

**Comment by bcdonovan** [comment]
Found the entry in .gitmodules. I'll add an line to readme.md to doc the need to pull the submodules.

**Comment by caryan** [comment]
Yep sorry about that.  It's also coming in libaps2.  Closed by 044e50ade227243ed5d11cf5d741130a8dcb7e3c
