### ISSUE TITLE
Kernel longer than samples causes stalling

### ISSUE THREAD

**Issue by dieris** [BBN-Q/libx6#26]
It would be nice if the driver truncated the kernel when longer than the sample number, maybe with a warning, instead of stalling.

**Comment by dieris** [comment]
I meant sample number / decimation factor

**Comment by blakejohnson** [comment]
That's a good suggestion.

**Comment by caryan** [comment]
There is a better longer term fix in hardware but until that lands then yes we should make things smoother in software.

**Comment by caryan** [comment]
Bump, caused issued yet again.

**Comment by caryan** [comment]
Fixed in firmware v0.10
