### ISSUE TITLE
Record length validation for demod

### ISSUE THREAD

**Issue by dieris** [BBN-Q/libx6#30]
Record length needs to be a multiple of 64 for demod streams.

**Comment by caryan** [comment]
Hmmm we are validating to a multiple of 32 [here](https://github.com/BBN-Q/libx6/blob/master/src/lib/X6_1000.cpp#L279) because that's the decimation factor.  I'm not sure why odd demod length don't work.

**Comment by caryan** [comment]
Looking at the firmware I think it has to do with the 128 bit wide data path for the II components.  Unfortunately II components don't have a tkeep notion so we get stuffed with zeros. This means the record length actually needs to be a multiple of 128: each complex demod point is packed into one 32 bit word and we need 4 words to get the 128bit data path and 4 words * 32 decimation factor = 128.
