### ISSUE TITLE
Build dependency for version.hpp

### ISSUE THREAD

**Issue by caryan** [BBN-Q/libx6#36]
version.hpp doesn't seem to update after it is first created.

Pinging @blakejohnson did you see any way to get this to be refreshed on each build?

**Comment by blakejohnson** [comment]
Hmm, fair point. I don't know off-hand how to force it to be re-created. I'll look into it, though.

**Comment by blakejohnson** [comment]
Seem like maybe we should use `ADD_CUSTOM_TARGET` instead?

https://cmake.org/pipermail/cmake/2007-March/013419.html
