### ISSUE TITLE
Check that threshold channel is valid 

### ISSUE THREAD

**Issue by dieris** [BBN-Q/libx6#43]
Python crashes consistently in [`set_threshold_invert`](https://github.com/BBN-Q/libx6/blob/fccc0fcb7153c596d0420ad1004b6f90bed0692d/src/python/libx6.py#L260) for integrated raw streams (`c=0`).

**Comment by caryan** [comment]
"crashes" as in segfaults?

**Comment by dieris** [comment]
I'm not sure, there is no error message other than 'Python stopped working'

**Comment by caryan** [comment]
Does the terminal you launched Python from show a stack trace?

**Comment by dieris** [comment]
No, it just exits Ipython immediately with no message

**Comment by dieris** [comment]
Actually, the debugger gives:
Unhandled exception at 0x00007FF90188EA1E (ucrtbase.dll)

**Comment by caryan** [comment]
This used to work right? Are you using the new conda install? I wonder if this is MSVC being pedantic about something.

**Comment by dieris** [comment]
I think this is the first time I'm using the X6 after the new conda install. This used to work before

**Comment by dieris** [comment]
Thresholds can only be set for fast integrators (b=0)
