### ISSUE TITLE
Dropping data with Auspex

### ISSUE THREAD

**Issue by gribeill** [BBN-Q/libx6#45]
X6 seems to drop data intermittently when run through Auspex:
![x6bad](https://user-images.githubusercontent.com/10247948/27203877-eff663ee-51f5-11e7-9afb-da21b44a52c4.png)

No apparent dependence on rep rate/number of samples.

**Comment by blakejohnson** [comment]
Is this with version `0.10` that's on our conda channel?

**Comment by grahamrow** [comment]
That is correct.

**Comment by grahamrow** [comment]
This was caused by an unrelated problem with the Holzworth driver.
