### ISSUE TITLE
dll no longer compatible with Matlab

### ISSUE THREAD

**Issue by gribeill** [BBN-Q/libx6#46]
Master branch libx6.dll crashes Matlab on `connect_X6` 🤕

**Comment by dieris** [comment]
Have you tried the conda [install](https://anaconda.org/BBN-Q/libx6)? This works fine on my system.

**Comment by matthewware** [comment]
I don't think we've tried any of the packages from the conda channel on Maxwell.  We'll give that a shot.

**Comment by gribeill** [comment]
Use Auspex!
