### ISSUE TITLE
-lpthread flag now necessary?

### ISSUE THREAD

**Issue by matthewware** [BBN-Q/libx6#52]
To get the library on master to compile, I had to add lpthread to the CXX _FLAGS:
```
#set compile flag for Linux
if(UNIX)
  add_definitions(-DLINUX=1)
  set(CMAKE_CXX_FLAGS "${CMAKE_C_FLAGS} -lpthread") ## WHY DO WE NOW NEED lpthread???
endif()
```
in CMakeLists.txt.  Did that sneak into the reqs or am I doing something silly?

**Comment by gribeill** [comment]
Yes, this is for setting the semaphore that lets auspex know whether or not the board is done...
